set(CMAKE_SYSTEM_NAME Petra)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(NOT DEFINED CMAKE_SYSROOT AND DEFINED ENV{SYSROOT_DIR})
    set(CMAKE_SYSROOT "$ENV{SYSROOT_DIR}")
endif()
if(NOT DEFINED CMAKE_FIND_ROOT_PATH AND DEFINED ENV{SYSROOT_DIR})
    set(CMAKE_FIND_ROOT_PATH "$ENV{SYSROOT_DIR}")
endif()

set(CMAKE_C_COMPILER x86_64-petra-gcc)
set(CMAKE_CXX_COMPILER x86_64-petra-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
