[package]
name = "petraos-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = "0.5"
log = "0.4"
bitflags = "2.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "petraos-kernel"
path = "src/main.rs"
test = false
required-features = ["binary-only"]

[[test]]
name = "pmm"
path = "tests/mm/pmm.rs"

[[test]]
name = "heap"
path = "tests/mm/heap.rs"

[[test]]
name = "vma"
path = "tests/mm/vma.rs"