[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
spin.workspace = true
xmas-elf = "0.10.0"
smoltcp = { version = "0.11.0", default-features = false, features = ["alloc", "medium-ethernet", "proto-ipv4", "proto-ipv6", "socket-udp", "socket-tcp", "socket-dhcpv4", "socket-dns"] }
font8x8 = { version = "0.3.1", default-features = false, features = ["unicode"] }
pc-keyboard = "0.7.0"
ps2-mouse = "0.1.4"
linkme = "0.3"

[dependencies.ostd]
version = "0.18.0"