sources:
  - name: pkg-config
    subdir: sources
    git: 'https://gitlab.freedesktop.org/pkg-config/pkg-config.git'
    tag: 'pkg-config-0.29.2'
    version: '0.29.2'
    tools_required:
      - host-autoconf-v2.69
      - host-automake-v1.16
      - host-libtool
    regenerate:
      - args: ['./autogen.sh']
        environ:
          NOCONFIGURE: 'yes'

packages:
  - name: pkg-config
    architecture: x86_64
    from_source: pkg-config
    tools_required:
      - host-gcc
      - host-autoconf-v2.69
      - host-automake-v1.16
      - host-libtool
    pkgs_required:
      - mlibc
    configure:
      - args:
          - '@THIS_SOURCE_DIR@/configure'
          - '--host=x86_64-petra'
          - '--prefix=/usr'
          - '--with-internal-glib'
          - '--disable-host-tool'
    build:
      - args: ['make', '-j@PARALLELISM@']
    install:
      - args: ['make', 'DESTDIR=@SYSROOT_DIR@', 'install-strip']
