pub mod chdir;
pub mod chmod;
pub mod chown;
pub mod close;
pub mod dup;
pub mod dup2;
pub mod dup3;
pub mod lseek;
pub mod mount;
pub mod open;
pub mod pipe;
pub mod read;
pub mod write;

pub use chdir::syscall_chdir;
pub use chmod::syscall_chmod;
pub use chown::syscall_chown;
pub use close::syscall_close;
pub use dup::syscall_dup;
pub use dup2::syscall_dup2;
pub use dup3::syscall_dup3;
pub use lseek::syscall_lseek;
pub use mount::syscall_mount;
pub use open::syscall_open;
pub use pipe::syscall_pipe2;
pub use read::syscall_read;
pub use write::syscall_write;

use crate::syscall::SyscallResult;
use crate::vm::vma::VmaManager;
use alloc::string::String;
use alloc::vec::Vec;
use ostd::Error;
