//! 8042 PS/2 Controller Interrupt Handlers.
//!
//! Handles hardware interrupts generated by the 8042 PS/2 keyboard/mouse controller.

use crate::arch::idt::InterruptStackFrame;
use crate::arch::interrupt::lapic;
use crate::arch::ports::Ports;
use crate::drivers::char::keyboard;

/// Interrupt vector assigned to the PS/2 Keyboard (ISA IRQ 1).
pub const KEYBOARD_VECTOR: u8 = 33;

/// PS/2 Keyboard interrupt handler.
pub extern "x86-interrupt" fn keyboard_handler(_stack_frame: &mut InterruptStackFrame) {
    // Drain pending bytes from 8042 controller output buffer.
    // Bit 0 of port 0x64 (OBF): Output buffer full
    // Bit 5 of port 0x64 (AUX): 0 = Keyboard (Port 1), 1 = Mouse (Port 2)
    loop {
        // SAFETY: Reading status port 0x64 has no side effects.
        let status = unsafe { Ports::inb(0x64) };
        if (status & 0x01) == 0 {
            break;
        }

        // SAFETY: Reading data port 0x60 clears the 8042 output buffer.
        let byte = unsafe { Ports::inb(0x60) };

        // Only process keyboard data (bit 5 clear). Mouse data (bit 5 set) is discarded for now.
        if (status & 0x20) == 0 {
            keyboard::handle_scancode(byte);
        }
    }

    // SAFETY: LAPIC is guaranteed to be initialized and active when receiving interrupts.
    unsafe {
        lapic::get_lapic().end_of_interrupt();
    }
}
